{{/*
Expand the chart name.
*/}}
{{- define "agent-sec-sidecar.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "agent-sec-sidecar.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Chart name and version as used by the chart label.
*/}}
{{- define "agent-sec-sidecar.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels.
*/}}
{{- define "agent-sec-sidecar.labels" -}}
helm.sh/chart: {{ include "agent-sec-sidecar.chart" . }}
{{ include "agent-sec-sidecar.selectorLabels" . }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}

{{/*
Selector labels.
*/}}
{{- define "agent-sec-sidecar.selectorLabels" -}}
app.kubernetes.io/name: {{ include "agent-sec-sidecar.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Absolute socket path injected into both containers.
*/}}
{{- define "agent-sec-sidecar.socketPath" -}}
{{- $mountPath := trimSuffix "/" .Values.runtime.mountPath -}}
{{- $relativePath := trimPrefix "/" .Values.runtime.socketRelativePath -}}
{{- printf "%s/%s" $mountPath $relativePath -}}
{{- end }}

{{/*
Persistent Qoder configuration path injected into the CLI container.
*/}}
{{- define "agent-sec-sidecar.qoderConfigPath" -}}
{{- $mountPath := trimSuffix "/" .Values.persistence.mountPath -}}
{{- $relativePath := trimPrefix "/" .Values.cli.qoder.persistentPaths.configRelativePath -}}
{{- printf "%s/%s" $mountPath $relativePath -}}
{{- end }}

{{/*
Persistent Qoder working directory injected into the CLI container.
*/}}
{{- define "agent-sec-sidecar.qoderWorkspacePath" -}}
{{- $mountPath := trimSuffix "/" .Values.persistence.mountPath -}}
{{- $relativePath := trimPrefix "/" .Values.cli.qoder.persistentPaths.workspaceRelativePath -}}
{{- printf "%s/%s" $mountPath $relativePath -}}
{{- end }}

{{/*
Persistent agent-sec data path injected into both containers.
*/}}
{{- define "agent-sec-sidecar.dataPath" -}}
{{- $mountPath := trimSuffix "/" .Values.persistence.mountPath -}}
{{- $relativePath := trimPrefix "/" .Values.persistence.dataRelativePath -}}
{{- printf "%s/%s" $mountPath $relativePath -}}
{{- end }}

{{/*
Data PVC name, either supplied by the user or generated by this chart.
*/}}
{{- define "agent-sec-sidecar.dataClaimName" -}}
{{- if .Values.persistence.persistentVolumeClaim.existingClaim -}}
{{- .Values.persistence.persistentVolumeClaim.existingClaim -}}
{{- else -}}
{{- printf "%s-data" (include "agent-sec-sidecar.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end }}

{{/*
Use the live PVC access modes when the claim already exists. This prevents an
upgrade from attempting to mutate an existing RWO claim into RWX and lets
strategy/replica validation reflect the storage that Kubernetes will mount.
*/}}
{{- define "agent-sec-sidecar.effectiveDataAccessModes" -}}
{{- $accessModes := .Values.persistence.persistentVolumeClaim.accessModes -}}
{{- if .Values.persistence.enabled -}}
{{- $claimName := include "agent-sec-sidecar.dataClaimName" . -}}
{{- $existing := lookup "v1" "PersistentVolumeClaim" .Release.Namespace $claimName -}}
{{- with $existing -}}
{{- $accessModes = .spec.accessModes | default $accessModes -}}
{{- end -}}
{{- end -}}
{{- dict "accessModes" $accessModes | toJson -}}
{{- end }}

{{/*
PVC name, either supplied by the user or generated by this chart.
*/}}
{{- define "agent-sec-sidecar.runtimeClaimName" -}}
{{- if .Values.runtime.volume.persistentVolumeClaim.existingClaim -}}
{{- .Values.runtime.volume.persistentVolumeClaim.existingClaim -}}
{{- else -}}
{{- printf "%s-runtime" (include "agent-sec-sidecar.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end }}

{{/*
Reject volume configurations that cannot preserve Pod-local UDS semantics.
*/}}
{{- define "agent-sec-sidecar.validateValues" -}}
{{- $volumeType := .Values.runtime.volume.type -}}
{{- $persistence := .Values.persistence | default dict -}}
{{- $persistenceMountPath := get $persistence "mountPath" -}}
{{- $dataRelativePath := get $persistence "dataRelativePath" -}}
{{- $qoderPersistentPaths := .Values.cli.qoder.persistentPaths -}}
{{- $dataAccessConfig := include "agent-sec-sidecar.effectiveDataAccessModes" . | fromJson -}}
{{- $dataAccessModes := get $dataAccessConfig "accessModes" -}}
{{- if not (has $volumeType (list "emptyDir" "persistentVolumeClaim")) -}}
{{- fail "runtime.volume.type must be emptyDir or persistentVolumeClaim" -}}
{{- end -}}
{{- if not (hasPrefix "/" .Values.runtime.mountPath) -}}
{{- fail "runtime.mountPath must be an absolute path" -}}
{{- end -}}
{{- if hasPrefix "/" .Values.runtime.socketRelativePath -}}
{{- fail "runtime.socketRelativePath must be relative to runtime.mountPath" -}}
{{- end -}}
{{- if regexMatch "(^|/)\\.\\.(/|$)" .Values.runtime.socketRelativePath -}}
{{- fail "runtime.socketRelativePath must not contain a parent-directory segment" -}}
{{- end -}}
{{- if or (not (kindIs "string" $persistenceMountPath)) (not (kindIs "string" $dataRelativePath)) -}}
{{- fail "persistence values are incomplete; when upgrading an older release, use --reset-then-reuse-values instead of --reuse-values" -}}
{{- end -}}
{{- if not (hasPrefix "/" $persistenceMountPath) -}}
{{- fail "persistence.mountPath must be an absolute path" -}}
{{- end -}}
{{- if hasPrefix "/" $dataRelativePath -}}
{{- fail "persistence.dataRelativePath must be relative to persistence.mountPath" -}}
{{- end -}}
{{- if empty $dataRelativePath -}}
{{- fail "persistence.dataRelativePath must not be empty" -}}
{{- end -}}
{{- if regexMatch "(^|/)\\.\\.(/|$)" $dataRelativePath -}}
{{- fail "persistence.dataRelativePath must not contain a parent-directory segment" -}}
{{- end -}}
{{- if $qoderPersistentPaths.enabled -}}
{{- range $name, $path := dict "configRelativePath" $qoderPersistentPaths.configRelativePath "workspaceRelativePath" $qoderPersistentPaths.workspaceRelativePath -}}
{{- if or (not (kindIs "string" $path)) (empty $path) -}}
{{- fail (printf "cli.qoder.persistentPaths.%s must be a non-empty string" $name) -}}
{{- end -}}
{{- if hasPrefix "/" $path -}}
{{- fail (printf "cli.qoder.persistentPaths.%s must be relative to persistence.mountPath" $name) -}}
{{- end -}}
{{- if regexMatch "(^|/)\\.\\.(/|$)" $path -}}
{{- fail (printf "cli.qoder.persistentPaths.%s must not contain a parent-directory segment" $name) -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- if eq $volumeType "persistentVolumeClaim" -}}
{{- if gt (int .Values.replicaCount) 1 -}}
{{- fail "persistentVolumeClaim mode supports replicaCount=1 only; use emptyDir for multiple Pods" -}}
{{- end -}}
{{- $pvc := .Values.runtime.volume.persistentVolumeClaim -}}
{{- if and (not $pvc.create) (not $pvc.existingClaim) -}}
{{- fail "set runtime.volume.persistentVolumeClaim.create=true or provide existingClaim" -}}
{{- end -}}
{{- end -}}
{{- if .Values.persistence.enabled -}}
{{- $dataPvc := .Values.persistence.persistentVolumeClaim -}}
{{- if and (not $dataPvc.create) (not $dataPvc.existingClaim) -}}
{{- fail "set persistence.persistentVolumeClaim.create=true or provide existingClaim" -}}
{{- end -}}
{{- if and (gt (int .Values.replicaCount) 1) (not (has "ReadWriteMany" $dataAccessModes)) -}}
{{- fail "persistence with replicaCount greater than 1 requires ReadWriteMany access" -}}
{{- end -}}
{{- end -}}
{{- end }}
